### ISSUE TITLE
Not Output & File Not Found

### ISSUE THREAD

**Issue by qq617564112** [hl475/vispek#1]
Hi I've tried to process my raw data following the instruction in CMD, windows 10;
However I just got empty folders, here's the console information:
 `D:\DataProcess>python -m Raw_data --in_path D:\DataProcess\data\ --out_path D:\DataProcess\output\ `
`D:\DataProcess\data\`
`D:\DataProcess\output\`
`find 224 csv files in path 'D:\\DataProcess\\data\\`
`Load data`
`find 3 classes in 'D:\\DataProcess\\data\\`
(if I use `class_name = re.split('(\d+)', temp[0])[0]` instead of 'apple' )

Same if I use the example

Here's one of my raw_file:
[A1Full_106002_20170828_153314.zip](https://github.com/hl475/vispek/files/1308939/A1Full_106002_20170828_153314.zip)

**Comment by hl475** [comment]
@qq617564112, the data you attached does not contain any header information on the top (not exactly same as the one I sent previously [A1Full_106002_20170828_153314.csv.zip](https://github.com/hl475/vispek/files/1309158/A1Full_106002_20170828_153314.csv.zip)) Hence I would not call yours raw data.

Instead, you should use file_io.py, please follow the instructions https://github.com/hl475/vispek#how-to-run-file_iopy
